// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Chart': string;
  'backBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
