// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appear': string;
  'button': string;
  'form': string;
  'forms': string;
}
export const cssExports: CssExports;
export default cssExports;
