// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    [x: string]: string | undefined;
    'info': string;
    'backBtn': string;
    'positive': string;
    'negative': string;
    'appear': string;
    'content': string;
  }
  export const cssExports: CssExports;
  export default cssExports;
  