// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Statistic': string;
  'appear': string;
  'minus': string;
  'plus': string;
}
export const cssExports: CssExports;
export default cssExports;
